csv_path: data/csv/
rdata_path: data/rdata/
sf_path: data/sf/
raster_path: data/raster/
plot_path: data/plots/
speciesID: 3
species_vector:
- pine
- spruce
- birch
municipID: 4
municipOriginalIDs:
- 1
- 11
- 13
- 18
municipalities:
- Espoo
- Turku
- Lahti
- Joensuu
